name: Job Variable Workflow

on: [push, workflow_dispatch]


env:
  DOCKER_URL: some.docker.url

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{env.DOCKER_URL}}/image:latest
    #if: contains('some.docker.url/image:latest123', DOCKER_IMAGE)
    steps:
      - name: Run a multi-line script
        run: |
          echo ${DOCKER_IMAGE}
