name: Step Variable Workflow

on: [push]

env:
  DOCKER_URL: some.docker.url
  TEST: test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_STR1: ${{env.TEST}}/abc2
    steps:
      - name: Run a multi-line script
        env:
          DOCKER_IMAGE: ${{env.DOCKER_URL}}/image:latest
          TEST_STR: ${{env.TEST}}/abc
        run: |
          echo ${TEST_STR}
