name: Step Variable Workflow

on: [push]

env:
  DOCKER_URL: some.docker.url
  TEST: 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains('test', env.TEST)
    steps:
      - name: Run a multi-line script
        env:
          DOCKER_IMAGE: ${{env.DOCKER_URL}}/image:latest
        run: |
          echo ${DOCKER_IMAGE}
